---
name: CI
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: container start
        run: docker-compose up -d
      - name: test on amazon linux 2023
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T amazonlinux2023 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"
      - name: test on redhat 8
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T redhat-ubi8 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"
      - name: test on redhat 9
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T redhat-ubi9 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"
      - name: test on ubuntu 22.04
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T ubuntu22.04 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"
      - name: container stop
        run: docker-compose down